config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: [ :index, :show]
  resources :users, only: [ :create, :new ]
  post '/sessions', to: 'sessions#create', as: 'sign_in'
  delete '/sessions', to: 'sessions#destroy', as: 'sign_out'
  get '/sessions' =>'sessions#create'
  resources :orders, only: [ :create, :show, :index, :destroy ]
  delete '/orders', to: 'orders#destroy_all', as: 'remove_all'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :users, through: :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :products, through: :orders

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+{2,}\z/}
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by_id(session[:user_id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < SecureController

  before_filter :find_order, only: [:destroy, :show]

  def index
    @orders = Order.all
    @user = current_user
  end

  def create
    @order = current_user.orders.create(product_id: params[:product_id])
    redirect_to @order
  end

  def show; end   # to have on one line, could not have at all, would still work

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  def destroy_all
    user = User.find(current_user.id)
    user.orders.clear
    redirect_to orders_path
  end

  private

  def find_order
    @order = current_user.orders.find(params[:id])
  end

  # def order_params
  #   params.require(:order).permit(:product_id)
  # end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @user = current_user
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/controllers/secure_controller.rb
class SecureController < ApplicationController
  before_filter :require_current_user

  def require_current_user
    redirect_to root_url unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: user_params[:email], password: user_params[:password])
    if @user
      session[:user_id] = @user.id
    else
      flash[:error] = 'Incorrect credientials'
    end
    redirect_to products_path
  end

  def destroy
    session.clear
    redirect_to products_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to products_path
    else
      render 'users/new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :address )
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FakerShoppingCart</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>


    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href=""></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to 'Products', products_path %>
                    </li>
                    <li>
                      <%= link_to 'Your cart', orders_path, method: 'get' %>

                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>



    <div id = "container">
      <header>
        <h1>faker.com</h1>
        <nav>
           <ul>
              <li>
                <button type="button" class='btn btn-primary'> <%= link_to 'Products', products_path %> </button>
              </li>
              <li>
                <%= button_to 'Your cart', orders_path, method: 'get' %>
              </li>
              <li>
                <%= button_to 'Sign Out', sign_out_path, method: 'delete' %>
              </li>
           </ul>
         </nav>
      </header>



      <main role="main">
        <%= yield %>
      </main>

      <footer>
        <p>faker.com &copy; 2015</p>
      </footer>
    </div>

  </body>
</html>

app/views/orders/index.html.erb
<div id = "cart-view">
  <h2> Welcome to your shopping cart <%= @user.name %> </h2>
  <br>
  <h3>Your orders</h3>
  <p>

  <ul>
    <% @user.orders.each do |order| %>
    <li>
      <%= order.id %> &nbsp;
      <%= order.try(:product).try(:name) %> &nbsp; &nbsp;
      <%= button_to 'Remove Item', order, method: 'delete' %>
    </li>
    <% end %>
  </ul>


  <%= button_to 'Remove All Items', remove_all_path, method: 'delete' %>

<!--   <form class = "remove-all" action="/delete_all_items" method="POST">
    <input type ="submit" value="Remove ALL items from your cart">
  </form> -->

</div>

app/views/orders/show.html.erb
<%= @order.user.name %>

<div id = "new-order-view">
  <h2>New order for: <%= @order.user.name %></h2>
  <h4>Order Number: <%= @order.id %></h4>

  <h3>You have added to your cart: </h3>
  <p>
  <h2><%= @order.product.name %></h2>
  <p><%= @order.product.description %></p>


  <%= button_to 'View Orders', orders_path, method: 'get' %>

<!--   <form action="/show_cart" method="post">
      <input type ="submit" value="View cart">
  </form> -->

</div>

app/views/products/index.html.erb
<% if @user %>
  <h4>Welcome to faker.com <%= @user.name %></h4>
<% end %>

<h1>Products</h1>

<div id = 'products_list'>
  <ul>
    <% @products.each do |product| %>
    <li>
      <h3> <%= link_to product.name, product_path(product) %> </h3>
   </li>
    <% end %>
  </ul>
  <p>To order products you will need to sign in or sign up.</p>
  <p>To view details of a product please follow the above links</p>
</div>


<% unless @user %>
  <div id = "sign_in_form">

    <%= form_for :user, url: sign_in_path do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email, {placeholder: "email"} %>

      <%= f.label :password %>
      <%= f.password_field :password, {placeholder: "password"} %>

      <%= f.submit 'Sign In' %>
    <% end %>

    <p><%= flash[:error] %></p>





    <%= button_to 'Sign Up', new_user_path, method: 'get' %>

  </div>

<% end %>

app/views/products/show.html.erb
<div id = "product-item-view">

  <h1><%= @product.name %></h1>

  <h3><%= @product.description %></h3>

  <p>Price: $<%= '%.2f' % @product.price %></p>


  <%= button_to 'Place Order', orders_path, params: {product_id: @product.id} %>

  <p>To place an order please sign in or create an account by signing up</p>

</div>

app/views/users/new.html.erb
<h2>Enter your details below to sign up
<br> to order products on facker.com</h2>

<div id = "sign_up_form">

  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, {placeholder: "name"} %>

    <%= f.label :email %>
    <%= f.text_field :email, {placeholder: "email"} %>

    <%= f.label :password %>
    <%= f.password_field :password, {placeholder: "password"} %>

    <%= f.label :address, 'Street Address' %>
    <%= f.text_field :address, {placeholder: "street address"} %>

    <%= f.submit 'Sign Up' %>

  <% end %>

  <% if !@user.errors.full_messages.empty? %>
    <%= 'Incorrect inforamtion, please try again' %>
  <% end %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %> </li>
    <% end %>
  </ul>

  </form>
</div>